name: CI - Lint & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: docker/Dockerfile
          ignore: DL3008

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.x'

      - name: Install and run pip-audit
        run: |
          python -m pip install pip-audit
          pip-audit -r docker/requirements.txt

      - name: Syntax-check fetcher.py
        run: python -m py_compile docker/fetcher.py

      - name: Build image (single-arch, load)
        run: |
          docker buildx build --load -f docker/Dockerfile -t ia-mirror:${{ github.sha }} docker

      - name: Create SBOM (syft)
        uses: anchore/sbom-action@v0.20.6
        with:
          image: ia-mirror:${{ github.sha }}

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: sbom
          path: sbom.json
