name: Release - multi-arch build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ia-mirror:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/ia-mirror:latest
          build-args: |
            IA_PYPI_VERSION=5.5.0

      - name: Create release entry (lightweight)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            docker/Dockerfile
            docker/entrypoint.sh
            docker/fetcher.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
